version: '3.8'
services:
  dialogpt:
    #restart: always
    build: dialogpt
    ports:
      - 8083:8083
    environment:
      - PORT=8083
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]